# Generated by Django 5.2.9 on 2026-01-05 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessibilityProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wheelchair_access", models.BooleanField(default=False)),
                ("accessible_toilets", models.BooleanField(blank=True, null=True)),
                ("quiet_space_available", models.BooleanField(blank=True, null=True)),
                ("additional_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LookupOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_type",
                    models.CharField(
                        choices=[
                            ("EVENT_CATEGORY", "Event Category"),
                            ("ACCESSIBILITY_LEVEL", "Accessibility Level"),
                        ],
                        max_length=50,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("option_type", "display_order", "label"),
            },
        ),
        migrations.CreateModel(
            name="SensoryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("location_text", models.CharField(max_length=255)),
                ("postcode", models.CharField(blank=True, max_length=20)),
                ("age_min", models.IntegerField(blank=True, null=True)),
                ("age_max", models.IntegerField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("booking_required", models.BooleanField(default=False)),
                ("booking_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accessibility_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event",
                        to="main.accessibilityprofile",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        limit_choices_to={"option_type": "EVENT_CATEGORY"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="main.lookupoption",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="accessibilityprofile",
            name="crowd_level",
            field=models.ForeignKey(
                limit_choices_to={"option_type": "CROWD_LEVEL"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="crowd_profiles",
                to="main.lookupoption",
            ),
        ),
        migrations.AddField(
            model_name="accessibilityprofile",
            name="lighting_conditions",
            field=models.ForeignKey(
                limit_choices_to={"option_type": "LIGHTING_CONDITION"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lighting_profiles",
                to="main.lookupoption",
            ),
        ),
        migrations.AddField(
            model_name="accessibilityprofile",
            name="noise_level",
            field=models.ForeignKey(
                limit_choices_to={"option_type": "NOISE_LEVEL"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="noise_profiles",
                to="main.lookupoption",
            ),
        ),
        migrations.AddField(
            model_name="accessibilityprofile",
            name="sensory_level",
            field=models.ForeignKey(
                limit_choices_to={"option_type": "SENSORY_LEVEL"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sensory_profiles",
                to="main.lookupoption",
            ),
        ),
        migrations.AddField(
            model_name="lookupoption",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Assign for sensory-related options. Leave blank for non-sensory options.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lookup_options",
                to="main.sensorycategory",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lookupoption",
            unique_together={("option_type", "code")},
        ),
    ]
