# Generated by Django 5.2.9 on 2026-01-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lookupoption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("category__isnull", True)),
                fields=("option_type", "code"),
                name="uniq_lookupoption_nonsensory_type_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="lookupoption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("category__isnull", False)),
                fields=("option_type", "category", "code"),
                name="uniq_lookupoption_sensory_type_cat_code",
            ),
        ),
    ]
