# Generated by Django 5.2.9 on 2026-01-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_lookupoption_uniq_lookupoption_nonsensory_type_code_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lookupoption",
            unique_together=set(),
        ),
    ]
